version: '3'
services:
  notification:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8000:8000
    container_name: notification
    stdin_open: true
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
    - GATEWAY_BASE_URL=$YOUR_GATEWAY_SERVICE_BASE_URL
    - JWT_SECRET=$YOUR_GATEWAY_SERVICE_JWT_SECRET
    - DATABASE_URL=$YOUR_DATABASE_URL
    - LOG_LEVEL=DEBUG
    entrypoint: /app/entrypoint.sh